### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by hugotiburtino** [claudevervoort/ltibootcamp#21]
When running
```python
auth_request_params = {
    'scope': 'open_id', #we only use the flow for OIDC, not to get an access token
    'response_type': 'id_token',
    'client_id': tool_info['client_id'],
    'login_hint': init_login_request['login_hint'],
    'lti_message_hint': init_login_request['lti_message_hint'],
    'response_mode': 'form_post', # with LTI we expect the user to already have a session in the platform
    'nonce': nonce, #a nonce compared to state should fail if replayed
    'state': orig_state, #state is optional
    'redirect_uri': redirect_uri
}

autopost_iframe('deeplinking', tool_info['oidc_auth_endpoint'], auth_request_params)
```

I get
```

AttributeError

AttributeError: 'str' object has no attribute 'decode'
Traceback (most recent call last)

    File "/home/hugo/ws/serlo/lti/ltibootcamp/.venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/hugo/ws/serlo/lti/ltibootcamp/.venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app

    response = self.handle_exception(e)

    File "/home/hugo/ws/serlo/lti/ltibootcamp/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/hugo/ws/serlo/lti/ltibootcamp/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/hugo/ws/serlo/lti/ltibootcamp/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/hugo/ws/serlo/lti/ltibootcamp/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

    File "/home/hugo/ws/serlo/lti/ltibootcamp/server/lti_platform.py", line 82, in oidc_authorization

    return render_template('postauthresponse.html', redirect_uri=redirect_uri, state=state, id_token=id_token.decode('utf-8'))

    AttributeError: 'str' object has no attribute 'decode'

```

The only way to get the `id_token` for the next block is printing it in the terminal.

*Python 3.8.10*

**Comment by hugotiburtino** [comment]
Same error at
`deep_linking_response_token = jwt.encode(deep_linking_response, notebook_private_key, 'RS256').decode()`

**Comment by claudevervoort** [comment]
hmm it's been a while, will try to run this thing up again. That may be coming from one of the lib updates? Will tell you if I find anything. BTW if you have any LTI question at large, don't hesitate to ping me too...

**Comment by claudevervoort** [comment]
ok just pushed a commit that just removes the decode - might have been neede back then but not on newer libs and python. It allowed me to move past that step. Hopefully it fixes it for you too...

**Comment by hugotiburtino** [comment]
I've tried that already and received the following error:

![image](https://user-images.githubusercontent.com/45924645/142512451-89351a1e-432d-4d80-9c2f-b20434078274.png)

And yes, I may have some questions. When I gather them, I'll contact you. Thanks for that.

**Comment by hugotiburtino** [comment]
Sorry, the 403 happened because the storeandshow extension wasn't correctly set. Now it is working
